### PR TITLE
Feature/pnorris/#9 add obio exports for chou suarez as well

### PR DESCRIPTION
**Pull request by dr0cloud**
This is an expansion of a previous PR#3 that enabled producing of OBIO surface solar downwelling direct and diffuse fluxes on OBIO bands. The previous PR worked for RRTMG only. This PR expands the facility to all three radiation codes. It is activated by putting SOLAR_TO_OBIO: .TRUE. in AGCM.rc and then associating the solar export fields DROBIO and DFOBIO either by exporting them in history or adding future connectivity to the OradBioGC. It is off by default and therefore zero-diff. Even if it is on, it is effectively zero-diff ... it only potentially produces two currently unused new exports, now for RRTMGP and Chou-Suarez as well as for RRTMG (PR#3).

### CODE REVIEW

**Comment by dr0cloud** [comment]
Oops, like last time I meant to merge this into develop first then main, not other way around. Can I change that now, or we can just do it in the reverse order as we did for PR#3?

**Comment by mathomp4** [comment]
I (or you) can change the base to be to `develop`. I can do it if you'd like

**Comment by dr0cloud** [comment]
Yes, thanks Matt, can you change to develop. Thanks, P.

Peter Norris, Ph.D.
Senior Research Scientist
Global Modeling and Assimilation Office (GMAO) / NASA Goddard Space Flight Center
Goddard Earth Sciences Technology and Research (GESTAR) II / University of Maryland, Baltimore County (UMBC)
Cell 240-505-1476




From: Matthew Thompson ***@***.***>
Reply-To: GEOS-ESM/GEOSradiation_GridComp ***@***.***>
Date: Thursday, December 1, 2022 at 12:18 PM
To: GEOS-ESM/GEOSradiation_GridComp ***@***.***>
Cc: "Norris, Peter M. (GSFC-610.1)[UNIVERSITY OF MARYLAND BALTIMORE CO]" ***@***.***>, Assign ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/GEOSradiation_GridComp] Feature/pnorris/#9 add obio exports for chou suarez as well (PR #10)


I (or you) can change the base to be to develop. I can do it if you'd like

**Review by mathomp4 — APPROVED** [review]
Approve!

**Pull request merged**
